# -*- coding: utf-8 -*-
"""Untitled-1 - Copy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10nYal2bPgJRskxqVFxajQpTtww4hBsx8

# **MFU TOEIC Assistant**
"""

# Member group 5:
# 6631501023  Jiranya Arun
# 6631501026 - Chanisara Pathrugsa
# 6631501067 - Nurulhuda Adam Ishaq
# 6631501081 - Phloiphailin Khampuk
# 6631501131 - Chaw Chaw Latt
# 6631501193 - Yoon Thedar Cho

"""## **PART 1 (DATA PREPROCESSING):**"""

import os

clean_data = """=========================================
[Topic: Arrival Time and Registration]
Q: ควรมาถึงสถานที่สอบก่อนกี่นาที? / How many minutes before the test should test takers arrive?
A (TH): ผู้เข้าสอบต้องมาถึงสถานที่สอบก่อนเวลาอย่างน้อย 60 นาที (หรือ 1 ชั่วโมง) และจุดลงทะเบียนจะปิดก่อนเวลาสอบ 15 นาที
A (EN): Test takers must arrive at least 60 minutes (or 1 hour) before the test time and registration closes 15 minutes before the test.
=========================================
[Topic: Items to Bring on Test Day (Golden Rule)]
Q: สิ่งที่ต้องเตรียมมาในวันเข้าสอบ TOEIC มีอะไรบ้าง? ต้องเตรียมเงินสดมาเท่าไหร่? / What items do I need to bring on test day? How much cash?
A (TH): สิ่งที่ต้องเตรียมมาในวันเข้าสอบมีดังนี้:
1. เอกสารยืนยันตัวตนฉบับจริง (บัตรประชาชน หรือ ใบขับขี่ หรือ พาสปอร์ต)
2. เงินสด 50 บาท (สำหรับชำระค่าจัดส่งผลสอบทาง EMS เท่านั้น)
*หมายเหตุ: ไม่ต้องเตรียมเครื่องเขียน (ปากกา ดินสอ ยางลบ) มาเอง ทางศูนย์สอบมีเตรียมไว้ให้ทุกคน
A (EN): You must bring: 1. Original Valid ID, Driver's License, or Passport 2. 50 Baht in cash (for the EMS score delivery fee). *Note: No need to bring stationery, the test center provides it.
=========================================
[Topic: Required ID - Foreign Nationals Special]
Q: ชาวต่างชาติใช้เอกสารอะไรเพิ่มเติม? / Additional documents for Foreign Nationals?
A (TH): พาสปอร์ตฉบับจริง พร้อมกับ บัตรนักศึกษา หรือ ใบอนุญาตทำงาน (Work Permit แบบเล่ม, สมาร์ทการ์ด หรือแอปฯ)
A (EN): Original Valid Passport AND Student ID OR Valid Work Permit (Physical, Smart Card, or App).
=========================================
[Topic: Prohibited Items]
Q: ห้ามนำสิ่งของใดเข้าห้องสอบ? / What items are prohibited?
A (TH): ห้ามนำอุปกรณ์อิเล็กทรอนิกส์ (มือถือ, นาฬิกา, หูฟัง), กระเป๋า, หนังสือ, เครื่องเขียนส่วนตัว, ยา, กุญแจ, และน้ำดื่ม เข้าห้องสอบ
A (EN): Electronic devices (phones, watches, earphones), bags, books, personal stationery, medicine, keys, and water are strictly prohibited.
=========================================
[Topic: Re-testing Lapse Dates]
Q: สอบซ้ำต้องเว้นกี่วัน? / What is the lapse date for re-testing?
A (TH): คนไทยและต่างชาติที่มีวีซ่า: เว้น 5 วันปฏิทิน / ต่างชาติไม่มีใบอนุญาตทำงาน: เว้น 14 วันปฏิทิน หากสอบก่อนกำหนดผลเป็นโมฆะ
A (EN): Thais & Foreigners with permit: wait 5 calendar days. Foreigners without permit: wait 14 calendar days.
=========================================
[Topic: Score Validity & MFU Exemption]
Q: ผลสอบมีอายุกี่ปี? นักศึกษามหาวิทยาลัยแม่ฟ้าหลวง (มฟล.) ที่จะสำเร็จการศึกษา สามารถเข้าสอบ TOEIC เพื่อนำผลคะแนนไปใช้แทนการสอบในรายวิชาภาษาอังกฤษ ได้หรือไม่? / Score validity and MFU exemption?
A (TH): ผลสอบอายุ 2 ปี นักศึกษา มหาวิทยาลัยแม่ฟ้าหลวง (มฟล.) ใช้คะแนน 785 ขึ้นไป แทนการสอบ Communicative English ได้
A (EN): Valid for 2 years. MFU students with 785+ can substitute the Communicative English exam.
=========================================
[Topic: Taking Photos at Test Site]
Q: ต้องเตรียมรูปถ่ายมาเองไหม? / Do I need to bring a photo?
A (TH): ไม่ต้องเตรียมรูปถ่ายมาเอง เจ้าหน้าที่จะถ่ายภาพผู้เข้าสอบ ณ จุดลงทะเบียนก่อนเข้าห้องสอบ
A (EN): No, you do not need to bring a photo. Staff will take your photo at the registration point before entering the test room.
=========================================
[Topic: Score Report Formats]
Q: แบบฟอร์มรายงานผลเป็นแบบใด? / What format is the TOEIC score report in?
A (TH): ใบรายงานผลมี 2 แบบคือ:
1. นักศึกษามหาวิทยาลัยแม่ฟ้าหลวง (มฟล.): ใบรายงานผลจะมีข้อมูลคะแนนแต่จะ "ไม่มีรูปภาพ"
2. บุคคลทั่วไป: ใบรายงานผลจะมีข้อมูลคะแนนและ "มีรูปภาพของผู้เข้าสอบ" ชัดเจน
A (EN): There are 2 formats:
1. MFU Students: The report contains score information but "no photo".
2. General Public: The report contains score information and a "clear photo of the examinee".
=========================================
[Topic: Dress Code]
Q: แต่งกายชุดแบบใด? / What is the dress code?
A (TH): ต้องแต่งกายด้วย "ชุดสุภาพ"
A (EN): Must wear "Polite Attire" or "Smart Casual".
=========================================
[Topic: Refund Policy]
Q: ขอคืนเงินได้หรือไม่? เมื่อชำระเงินค่าสมัครสอบแล้ว ไม่มาสอบตามกำหนด สามารถขอเงินค่าสมัครสอบคืนได้หรือไม่? / Can I request a refund?
A (TH): ไม่สามารถขอคืนเงินได้ทุกกรณี
A (EN): No. It is non-refundable in all cases.
=========================================
[Topic: Registration Channels]
Q: สมัครสอบผ่านช่องทางใด? / Registration channels?
A (TH): สมัครผ่านเว็บไซต์ https://toeic.mfu.ac.th เท่านั้น
A (EN): Register only through the official website at https://toeic.mfu.ac.th
=========================================
[Topic: MFU Student Test Categories]
Q: นักศึกษามหาวิทยาลัยแม่ฟ้าหลวง (มฟล.) เลือกสอบประเภทใดได้บ้าง? / Which categories can MFU students choose?
A (TH): เลือกได้ 2 ประเภท: 1. ประเภทนักศึกษามหาวิทยาลัยแม่ฟ้าหลวง (มฟล.) หรือ 2. ประเภทบุคคลทั่วไป
A (EN): 1. MFU Student category or 2. Personal/General Public category.
=========================================
"""

filename = "TOEIC_RAG_QA_Bilingual.txt"
with open(filename, "w", encoding="utf-8") as file:
    file.write(clean_data)

print(f"✅ Success! {filename} has been created/updated.")

"""## **PART 2 (RAG PIPELINE):**"""

import os
os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"

import os
import re

# ==========================================
# 0. SETUP GOOGLE API KEY
# ==========================================
os.environ["GOOGLE_API_KEY"] = "AIzaxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate

# Fix: Changed from langchain_classic to langchain
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain.chains import create_retrieval_chain

# ==========================================
# 1. LOAD DATA & VECTOR STORE
# ==========================================
print("กำลังโหลดข้อมูลและสร้าง Vector Store...")
try:
    loader = TextLoader("TOEIC_RAG_QA_Bilingual.txt", encoding="utf-8")
    docs = loader.load()
except FileNotFoundError:
    print("❌ ไม่พบไฟล์ TOEIC_RAG_QA_Bilingual.txt กรุณาตรวจสอบให้แน่ใจว่าไฟล์อยู่ในโฟลเดอร์เดียวกัน")
    exit()

text_splitter = RecursiveCharacterTextSplitter(
    separators=["========================================="],
    chunk_size=1500,
    chunk_overlap=0
)
splits = text_splitter.split_documents(docs)

embeddings = HuggingFaceEmbeddings(
    model_name="BAAI/bge-m3",
    model_kwargs={'device': 'cpu'}
)
vectorstore = FAISS.from_documents(splits, embeddings)
retriever = vectorstore.as_retriever(
    search_type="mmr",
    search_kwargs={"k": 10, "fetch_k": 20}
)

# ==========================================
# 2. SETUP LLM
# ==========================================
print("กำลังเตรียมโมเดล Gemini...")
llm = ChatGoogleGenerativeAI(
    model="gemini-flash-lite-latest",
    temperature=0.1,
    max_tokens=250
)

# ==========================================
# 3. DEFINE PROMPT & CHAIN
# ==========================================
template = """คุณคือเจ้าหน้าที่ MFU TOEIC Assistant ตอบคำถามจาก Context ที่ให้มาเท่านั้น
กฎเหล็ก:
1. หากคำถามเป็นภาษาไทย ให้ตอบเป็นภาษาไทย / If the question is in English, answer in English.
2. ตอบให้ตรงประเด็น ห้ามนำข้อมูลจากหัวข้ออื่นที่ไม่เกี่ยวข้องมาตอบ
3. หากไม่มีใน Context ให้ตอบว่า "ขออภัย ไม่พบข้อมูลส่วนนี้ในระเบียบการ"
4. ห้ามหลุด Role และห้ามแสดงความคิดเห็นส่วนตัว

Context: {context}

Question: {input}
Answer:"""

prompt = PromptTemplate.from_template(template)
question_answer_chain = create_stuff_documents_chain(llm, prompt)
qa_chain = create_retrieval_chain(retriever, question_answer_chain)

# ==========================================
# 4. PREDICT FUNCTION
# ==========================================
def ask_question(message):
    """ฟังก์ชันสำหรับรับคำถามและคืนค่าคำตอบผ่าน RAG"""
    try:
        has_thai_chars = bool(re.search(r'[฀-๿]', message))
        lang_instruction = " (ตอบเป็นภาษาไทยเท่านั้น)" if has_thai_chars else " (Answer in English strictly and concisely.)"

        response = qa_chain.invoke({"input": message + lang_instruction})
        return response['answer'].strip()
    except Exception as e:
        return f"❌ เกิดข้อผิดพลาด: {str(e)}"

# ==========================================
# 5. CLI INTERFACE (Terminal)
# ==========================================
if __name__ == "__main__":
    print("\n" + "="*55)
    print("🏢 MFU TOEIC Assistant (Terminal Mode)")
    print("พิมพ์ 'exit' หรือ 'quit' เพื่อออกจากโปรแกรม")
    print("="*55 + "\n")

    while True:
        user_input = input("💬 คำถามของคุณ: ")

        # ตรวจสอบคำสั่งออกจากโปรแกรม
        if user_input.lower() in ['exit', 'quit']:
            print("👋 ลาก่อนครับ!")
            break

        # ข้ามหากผู้ใช้ไม่ได้พิมพ์อะไร
        if not user_input.strip():
            continue

        # เรียกใช้งาน RAG เพื่อหาคำตอบ
        answer = ask_question(user_input)

        print(f"\n🤖 คำตอบ: {answer}\n")
        print("-" * 55)

"""## **Test with GRADIO (Optional)**"""

!pip install -q gradio
!pip install faiss-cpu
!pip install -qU langchain langchain-community langchain-core langchain-huggingface langchain-google-genai langchain-text-splitters sentence-transformers pypdf

import os
import re
import gradio as gr

# ==========================================
# 0. SETUP GOOGLE API KEY
# ==========================================
os.environ["GOOGLE_API_KEY"] = "AIzaxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate

# 🎯 จุดสำคัญที่แก้ให้แล้ว: ใช้ langchain_classic
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_classic.chains import create_retrieval_chain

# ==========================================
# 1. LOAD DATA & VECTOR STORE
# ==========================================
print("กำลังโหลดข้อมูลและสร้าง Vector Store...")
loader = TextLoader("TOEIC_RAG_QA_Bilingual.txt", encoding="utf-8")
docs = loader.load()

text_splitter = RecursiveCharacterTextSplitter(
    separators=["========================================="],
    chunk_size=1500,
    chunk_overlap=0
)
splits = text_splitter.split_documents(docs)

embeddings = HuggingFaceEmbeddings(
    model_name="BAAI/bge-m3",
    model_kwargs={'device': 'cpu'}
)
vectorstore = FAISS.from_documents(splits, embeddings)
retriever = vectorstore.as_retriever(
    search_type="mmr",
    search_kwargs={"k": 10, "fetch_k": 20}
)

# ==========================================
# 2. SETUP LLM
# ==========================================
print("กำลังเตรียมโมเดล Gemini 1.5 Flash...")
llm = ChatGoogleGenerativeAI(
    model="gemini-flash-lite-latest",
    temperature=0.1,
    max_tokens=250
)

# ==========================================
# 3. DEFINE PROMPT & CHAIN
# ==========================================
template = """คุณคือเจ้าหน้าที่ MFU TOEIC Assistant ตอบคำถามจาก Context ที่ให้มาเท่านั้น
กฎเหล็ก:
1. หากคำถามเป็นภาษาไทย ให้ตอบเป็นภาษาไทย / If the question is in English, answer in English.
2. ตอบให้ตรงประเด็น ห้ามนำข้อมูลจากหัวข้ออื่นที่ไม่เกี่ยวข้องมาตอบ
3. หากไม่มีใน Context ให้ตอบว่า "ขออภัย ไม่พบข้อมูลส่วนนี้ในระเบียบการ"
4. ห้ามหลุด Role และห้ามแสดงความคิดเห็นส่วนตัว

Context: {context}

Question: {input}
Answer:"""

prompt = PromptTemplate.from_template(template)
question_answer_chain = create_stuff_documents_chain(llm, prompt)
qa_chain = create_retrieval_chain(retriever, question_answer_chain)

# ==========================================
# 4. PREDICT FUNCTION
# ==========================================
def predict(message, history):
    try:
        has_thai_chars = bool(re.search(r'[\u0E00-\u0E7F]', message))
        lang_instruction = " (ตอบเป็นภาษาไทยเท่านั้น)" if has_thai_chars else " (Answer in English strictly and concisely.)"

        response = qa_chain.invoke({"input": message + lang_instruction})
        return response['answer'].strip()
    except Exception as e:
        return f"❌ เกิดข้อผิดพลาด: {str(e)}"

# ==========================================
# 5. GRADIO INTERFACE
# ==========================================
with gr.Blocks(theme="soft") as demo:
    gr.Markdown("# 🏢 MFU TOEIC Assistant (Powered by Gemini)")
    gr.Markdown("### ระบบตอบคำถามระเบียบการสอบ TOEIC มหาวิทยาลัยแม่ฟ้าหลวง")

    gr.ChatInterface(
        fn=predict,
        examples=[
            "ต้องเตรียมเงินสดมาเท่าไหร่ในวันสอบ?",
            "ชำระเงินแล้วขอคืนเงินได้ไหม?",
            "การแต่งกายเข้าสอบต้องใส่ชุดแบบไหน?"
        ]
    )

if __name__ == "__main__":
    demo.launch(debug=True)

"""## **PRAT 3 (DEPLOYMENT):**"""

!pip install streamlit -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import os
# import re
# from langchain_community.document_loaders import TextLoader
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from langchain_huggingface import HuggingFaceEmbeddings
# from langchain_community.vectorstores import FAISS
# from langchain_google_genai import ChatGoogleGenerativeAI
# from langchain_core.prompts import PromptTemplate
# from langchain.chains.combine_documents import create_stuff_documents_chain
# from langchain.chains import create_retrieval_chain
# 
# # ==========================================
# # 0. SETUP & CONFIGURATION
# # ==========================================
# st.set_page_config(page_title="MFU TOEIC Assistant", page_icon="🏢")
# 
# # ดึง API Key จาก Streamlit Secrets (ตั้งค่าในหน้าเว็บ Streamlit Cloud)
# if "GOOGLE_API_KEY" not in st.secrets:
#     st.error("กรุณาตั้งค่า GOOGLE_API_KEY ใน Streamlit Secrets ก่อนใช้งาน")
#     st.stop()
# 
# os.environ["GOOGLE_API_KEY"] = st.secrets["GOOGLE_API_KEY"]
# 
# # ==========================================
# # 1. LOAD DATA & VECTOR STORE (Caching เพื่อความเร็ว)
# # ==========================================
# @st.cache_resource
# def init_rag_system():
#     # โหลดไฟล์ (ตรวจสอบว่าไฟล์ TOEIC_RAG_QA_Bilingual.txt อยู่ใน repo เดียวกัน)
#     loader = TextLoader("TOEIC_RAG_QA_Bilingual.txt", encoding="utf-8")
#     docs = loader.load()
# 
#     text_splitter = RecursiveCharacterTextSplitter(
#         separators=["========================================="],
#         chunk_size=1500,
#         chunk_overlap=0
#     )
#     splits = text_splitter.split_documents(docs)
# 
#     # ใช้ CPU สำหรับ HuggingFace บน Streamlit Cloud
#     embeddings = HuggingFaceEmbeddings(
#         model_name="BAAI/bge-m3",
#         model_kwargs={'device': 'cpu'}
#     )
# 
#     vectorstore = FAISS.from_documents(splits, embeddings)
#     return vectorstore.as_retriever(
#         search_type="mmr",
#         search_kwargs={"k": 5, "fetch_k": 10} # ปรับ k ลงเล็กน้อยเพื่อความเร็ว
#     )
# 
# retriever = init_rag_system()
# 
# # ==========================================
# # 2. SETUP LLM & CHAIN
# # ==========================================
# llm = ChatGoogleGenerativeAI(
#     model="gemini-1.5-flash", # แนะนำให้ใช้ชื่อมาตรฐาน
#     temperature=0.1,
#     max_tokens=500
# )
# 
# template = """คุณคือเจ้าหน้าที่ MFU TOEIC Assistant ตอบคำถามจาก Context ที่ให้มาเท่านั้น
# กฎเหล็ก:
# 1. หากคำถามเป็นภาษาไทย ให้ตอบเป็นภาษาไทย / If the question is in English, answer in English.
# 2. ตอบให้ตรงประเด็น ห้ามนำข้อมูลจากหัวข้ออื่นที่ไม่เกี่ยวข้องมาตอบ
# 3. หากไม่มีใน Context ให้ตอบว่า "ขออภัย ไม่พบข้อมูลส่วนนี้ในระเบียบการ"
# 4. ห้ามหลุด Role และห้ามแสดงความคิดเห็นส่วนตัว
# 
# Context: {context}
# 
# Question: {input}
# Answer:"""
# 
# prompt = PromptTemplate.from_template(template)
# question_answer_chain = create_stuff_documents_chain(llm, prompt)
# qa_chain = create_retrieval_chain(retriever, question_answer_chain)
# 
# # ==========================================
# # 3. STREAMLIT UI
# # ==========================================
# st.title("🏢 MFU TOEIC Assistant")
# st.markdown("ระบบตอบคำถามระเบียบการสอบ TOEIC มหาวิทยาลัยแม่ฟ้าหลวง")
# 
# # สร้าง Chat History ใน Session State
# if "messages" not in st.session_state:
#     st.session_state.messages = []
# 
# # แสดงข้อความเก่า
# for message in st.session_state.messages:
#     with st.chat_message(message["role"]):
#         st.markdown(message["content"])
# 
# # ส่วนรับคำถาม
# if prompt_input := st.chat_input("พิมพ์คำถามที่นี่..."):
#     # แสดงคำถามผู้ใช้
#     st.session_state.messages.append({"role": "user", "content": prompt_input})
#     with st.chat_message("user"):
#         st.markdown(prompt_input)
# 
#     # ประมวลผลคำตอบ
#     with st.chat_message("assistant"):
#         with st.spinner("กำลังหาคำตอบ..."):
#             try:
#                 # ตรวจสอบภาษา
#                 has_thai_chars = bool(re.search(r'[\u0E00-\u0E7F]', prompt_input))
#                 lang_instruction = " (ตอบเป็นภาษาไทย)" if has_thai_chars else " (Answer in English)"
# 
#                 response = qa_chain.invoke({"input": prompt_input + lang_instruction})
#                 full_response = response['answer'].strip()
# 
#                 st.markdown(full_response)
#                 st.session_state.messages.append({"role": "assistant", "content": full_response})
#             except Exception as e:
#                 error_msg = f"❌ เกิดข้อผิดพลาด: {str(e)}"
#                 st.error(error_msg)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# langchain
# langchain-community
# langchain-google-genai
# langchain-huggingface
# faiss-cpu
# sentence-transformers
# pypdf

import zipfile
import os
from google.colab import files

# Define your project files
# Added the .docx file and the folder logic
files_to_zip = [
    'app.py',
    'requirements.txt',
    'TOEIC_RAG_QA_Bilingual.txt'
]

folder_to_zip = 'faiss_index'
zip_name = 'BDA_Project2_Group5.zip'

with zipfile.ZipFile(zip_name, 'w', zipfile.ZIP_DEFLATED) as zipf:
    # 1. Add individual files
    for file in files_to_zip:
        if os.path.exists(file):
            zipf.write(file)
            print(f"Added file: {file}")
        else:
            print(f"⚠️ Warning: {file} not found!")

    # 2. Add the FAISS folder and its contents
    if os.path.exists(folder_to_zip):
        for root, dirs, files_in_folder in os.walk(folder_to_zip):
            for file in files_in_folder:
                file_path = os.path.join(root, file)
                # This ensures the folder structure is preserved in the zip
                zipf.write(file_path, os.path.relpath(file_path, os.path.join(folder_to_zip, '..')))
        print(f"Added folder: {folder_to_zip}")

print(f"\n✅ ZIP created: {zip_name}")

# Trigger download to your computer
files.download(zip_name)